version: '3.9'
services:

  ftp:
    container_name: ftp
    image: bogem/ftp
    ports:
      - "20:20"
      - "21:21"
      - "47400-47470:47400-47470"
    env_file: ../ftp.env
    restart: always
    networks:
      - bubble

networks:
  bubble:
    external: true